############################################
################  Species  #################
############################################

species: "mouse"


############################################
############  Files  locations  ############
############################################

references:
  indexes:
    human: "/home/data/kallisto_index/homo_sapiens/transcriptome.idx"
    mouse: "/home/data/kallisto_index/mus_musculus/transcriptome.idx"
  fasta:
    human: "/home/data/kallisto_index/homo_sapiens/Homo_sapiens.GRCh38.cdna.all.fa"
    mouse: "/home/data/kallisto_index/mus_musculus/Mus_musculus.GRCm38.cdna.all.fa"

# Not used for the moment
ChromInfo:
  human: "kallisto_files/ChromInfo_human"
  mouse: "kallisto_files/ChromInfo_mouse"

gtf:
  human: "/home/data/kallisto_index/homo_sapiens/Homo_sapiens.GRCh38.96.gtf"
  mouse: "/home/data/kallisto_index/mus_musculus/Mus_musculus.GRCm38.96.gtf"

fastq:
  directory: "path/to/files/"
  human: "/data1/scratch/pamesl/projet_RNAseq_Gaetano/HN00115059/homo_sapiens_analysis/"
  mouse: "/data1/scratch/pamesl/projet_RNAseq_Gaetano/HN00115059/mus_musculus_analysis/"

sample_sheet: "config/samples.tsv"

############################################
############  Tools parameters  ############
############################################

kallisto:
  directory: "results/kallisto_results/"
  index:
    nthread: 5
  quant:
    nthread: 10
    bootstrap: 100
